name: compile

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate PDF document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
          latexmk_shell_escape: true
          post_compile: "latexmk -c"
      - name: upload pdf file
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
