name: latexmk
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yegor256/latexmk-action@0.4.0
        with:
          cmd: latexmk
          path: .
          opts: -pdf
          packages: pgfplots mlmodern noto-mono
